<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">    
    <title>Day Tokens Calculator</title>
    <meta content="Calculator of Day Tokens generated by TimeMint. A simple website to check your Days income over the Ages." name="description">
    <link href='https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Material+Icons' rel="stylesheet">
    <link href="https://unpkg.com/vuetify/dist/vuetify.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/6.6.10/sweetalert2.min.css" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/png" href="favicon-32x32.png" sizes="32x32" />
    <link rel="icon" type="image/png" href="favicon-16x16.png" sizes="16x16" />

</head>
<body>

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-105822545-1', 'auto');
      ga('send', 'pageview');

    </script>

    <div id="app">

        <v-app>
            <main>
                <template>
                    <v-toolbar dark>
                        <v-toolbar-title class="white--text">
                            {{ $t('calcDayTokens') }}
                        </v-toolbar-title>
                        <v-spacer></v-spacer>

                        <template>
                            <div class="text-xs-center">
                                <v-bottom-sheet>
                                    <v-btn v-tooltip:bottom="{ html: $t('selectYourLanguage') }" slot="activator" icon>
                                        <v-icon>language</v-icon>
                                    </v-btn>
                                    <v-list>
                                        <v-subheader>{{ $t('selectYourLanguage') }}</v-subheader>
                                            <v-list-tile v-on:click="i18n.locale = locale" v-for="(s, locale) in localeStrings">
                                                <v-list-tile-avatar>
                                                    <v-avatar size="32px" tile>
                                                        <img width="32px" :src="'/assets/img/flags/' + s.flag + '.png'">
                                                    </v-avatar>
                                                </v-list-tile-avatar>
                                            <v-list-tile-title>{{ $t(s.flag) }}</v-list-tile-title>
                                    </v-list-tile>
                                  </v-list>
                                </v-bottom-sheet>
                            </div>
                        </template>

                        <v-dialog lazy absolute width="50%">
                            <v-btn slot="activator" v-tooltip:bottom="{ html: $t('coffe') }" icon>
                                <v-icon>free_breakfast</v-icon>
                            </v-btn>
                            <v-card>
                                <v-card-title>
                                    <div class="headline">{{ $t('coffeTxt') }}</div>
                                </v-card-title>
                                <v-card-text>
                                    <pre>ETH ADDRESS: <a target="_blank" :href="'https://etherscan.io/address/' + $t('coffe_address')">{{ $t('coffe_address') }}</a></pre>
                                </v-card-text>
                            </v-card>
                        </v-dialog>

                        <v-menu
                            offset-x
                            :close-on-content-click="false"
                            :nudge-width="300"
                            v-model="menu"
                            >
                            <v-btn v-tooltip:bottom="{ html: $t('feedback') }" icon slot="activator">
                                <v-icon v-on:click="menu = true">{{ $t('feedback') }}</v-icon>
                            </v-btn>
                            <v-card>
                                <v-list>
                                    <v-list-tile>
                                        <v-list-tile-title>{{ $t('sendFeedback') }}</v-list-tile-title>
                                    </v-list-tile>
                                </v-list>
                                <v-list>
                                    <v-container fluid>
                                        <v-layout row>
                                            <v-flex xs12>
                                                <template v-if="loadingFeedback">
                                                    <v-progress-circular v-bind:size="50" indeterminate class="primary--text"></v-progress-circular>
                                                </template>
                                                <template v-else>
                                                    <v-text-field
                                                    name="feedback"
                                                    :label="$t('writeMessage')"
                                                    textarea
                                                    v-model="message"
                                                    ></v-text-field>
                                                </template>
                                            </v-flex>
                                        </v-layout>
                                    </v-container>
                                </v-list>
                                <v-card-actions>
                                    <v-spacer></v-spacer>
                                    <v-btn :disabled="loadingFeedback" primary flat v-on:click="send()">
                                        {{ $t('send') }}
                                    </v-btn>
                                </v-card-actions>
                            </v-card>
                        </v-menu>
                    </v-toolbar>
                    <v-card flat class="primary white--text text-xs-center">
                        <v-card-text>
                            {{ $t('infoTableChrono') }} <a class="white--text" target="_blank" href="https://blog.chronologic.network/timemint-assignments-615f859bdc12">link</a>.
                            {{ $t('seeTable') }}, <a class="white--text" target="_blank" href="https://docs.google.com/spreadsheets/d/141PDSDLQBOdLy5bejWxTUQd0ZDuM6bPc1P5N_s96n20/edit?usp=sharing">{{ $t('clickHere') }}</a>.
                        </v-card-text>
                    </v-card>
                </template>
                <template>
                    <v-card class="grey lighten-3 elevation-0">
                        <v-card-text>
                            <v-container grid-list-md text-xs-center>
                                <v-layout row wrap>
                                    <v-flex md3 xs12>
                                        <v-subheader>
                                            {{ $t('typeAdressEth') }}
                                        </v-subheader>
                                    </v-flex>
                                    <v-flex md9 xs12>
                                        <v-text-field
                                            name="etheriumAddress"
                                            :label="$t('typeAdressEth')"
                                            id="etheriumAddress"
                                            v-model.lazy="form.etheriumAddress"
                                            v-on:blur="getAddress()"
                                        ></v-text-field>
                                    </v-flex>
                                    <v-flex md3 xs12>
                                        <v-subheader>
                                            {{ $t('ethInitial') }}
                                        </v-subheader>
                                    </v-flex>
                                    <v-flex md9 xs12>
                                        <v-text-field
                                            name="etherium"
                                            :label="$t('ethInvest')"
                                            id="etherium"
                                            v-model.lazy="form.etherium"
                                            suffix="ETH"
                                            v-on:blur="formEtherium(form.etherium)"
                                            :hint="$t('typeSeparator')"
                                        ></v-text-field>
                                    </v-flex>
                                    <v-flex md3 xs12>
                                        <v-subheader>
                                            TimeMint
                                        </v-subheader>
                                    </v-flex>
                                    <v-flex md9 xs12>
                                        <v-text-field
                                            name="timemint"
                                            :label="$t('numberTimemint')"
                                            id="timemint"
                                            v-model.lazy="form.timeMint"
                                            type="number"
                                            :max="form.max"
                                            :min="form.min"
                                        ></v-text-field>
                                    </v-flex>
                                    <v-flex md3 xs12>
                                        <v-subheader>
                                            ChronoPower
                                        </v-subheader>
                                    </v-flex>
                                    <v-flex md9 xs12>
                                        <v-text-field
                                            name="chronoPower"
                                            id="chronoPower"
                                            v-model="form.chronoPower"
                                            type="number"
                                            suffix="%"
                                            :label="$t('typeYourTimemint')"
                                            :readonly="true"
                                        ></v-text-field>
                                    </v-flex>
                                </v-layout>
                            </v-container>
                        </v-card-text>
                    </v-card>
                </template>

                <template>
                    <v-card class="grey lighten-4 elevation-0">
                        <v-card-text>
                            <v-container>
                                <v-layout row wrap>
                                    <v-flex md3 xs12>
                                        <v-subheader>
                                            {{ $t('days0') }}
                                        </v-subheader>
                                    </v-flex>
                                    <v-flex md9 xs12>
                                        <v-text-field
                                            name="tokensDayZero"
                                            id="tokensDayZero"
                                            v-model="form.tokensDayZero"
                                            type="number"
                                            suffix="DAYS"
                                            :placeholder="$t('typeEthDay0')"
                                            :readonly="true"
                                        ></v-text-field>
                                    </v-flex>
                                </v-layout>
                            </v-container>
                        </v-card-text>
                    </v-card>
                </template>

                <template>
                    <div>
                        <v-tabs dark v-model="active" centered>
                            <v-tabs-bar class="primary">
                                <v-tabs-item key="tab-01" href="#tab-01" ripple>{{ $t('simulation') }}</v-tabs-item>
                                <v-tabs-item key="tab-02" href="#tab-02" ripple>{{ $t('simulationInDays') }}</v-tabs-item>
                                <v-tabs-item key="tab-03" href="#tab-03" ripple>{{ $t('periods') }}</v-tabs-item>
                                <v-tabs-item key="tab-04" href="#tab-04" ripple>{{ $t('faq') }}</v-tabs-item>
                                <v-tabs-slider class="dark"></v-tabs-slider>
                            </v-tabs-bar>
                            <v-tabs-items>
                                <v-tabs-content key="tab-03" id="tab-03">
                                    <template>
                                        <v-container grid-list-md>
                                            <v-layout row wrap>
                                                <v-flex md12 xs12>
                                                    <table class="table">
                                                        <thead>
                                                            <tr>
                                                                <th class="text-xs-left">{{ $t('year') }}</th>
                                                                <th class="text-xs-left">{{ $t('cicle') }}</th>
                                                                <th class="text-xs-left">{{ $t('start') }}</th>
                                                                <th class="text-xs-left">{{ $t('end') }}</th>
                                                                <th class="text-xs-left" width="150">{{ $t('effective') }}</th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>
                                                            <tr v-for="(item, periodo) in chronoEra">
                                                                <td>{{ item.era }}</td>
                                                                <td>{{ periodo }}</td>
                                                                <td>
                                                                    <v-chip v-tooltip:top="{ html: getDay(item.initDay) }">
                                                                        <span class="bold">{{ item.initDay.toFixed(16) }}</span>
                                                                    </v-chip>
                                                                </td>
                                                                <td>
                                                                    <v-chip v-tooltip:top="{ html: getDay(item.lastDay) }">
                                                                        <span class="bold">{{ item.lastDay.toFixed(16) }}</span>
                                                                    </v-chip>
                                                                </td>
                                                                <td>{{ item.effective.toFixed(16) }}%</td>
                                                            </tr>
                                                        </tbody>
                                                    </table>
                                                </v-flex>
                                            </v-layout>
                                        </v-container>
                                    </template>
                                </v-tabs-content>
                                <v-tabs-content key="tab-01" id="tab-01">
                                    <template>
                                        <v-container grid-list-md>
                                            <v-layout row wrap v-if="canSimulate">
                                                <v-flex md12 xs12>
                                                    <table class="table">
                                                        <thead>
                                                            <tr>
                                                                <th class="text-xs-left">{{ $t('year') }}</th>
                                                                <th class="text-xs-left">{{ $t('chronoEra') }}</th>
                                                                <th class="text-xs-left">{{ $t('chronoPower') }}</th>
                                                                <th class="text-xs-left">{{ $t('vlSta') }}</th>
                                                                <th class="text-xs-left">{{ $t('vlEnd') }}</th>
                                                                <th class="text-xs-left">{{ $t('winPeriod') }}</th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>
                                                            <tr v-for="(simulation, chave) in simulations">
                                                                <td>{{ Math.ceil((chave+1) / 4) }}</td>
                                                                <td>{{ simulation.period }}</td>
                                                                <td>{{ simulation.chronoPower.toFixed(16) }}</td>
                                                                <td>{{ simulation.start.toFixed(16) }}</td>
                                                                <td>{{ simulation.last.toFixed(16) }}</td>
                                                                <td>{{ simulation.diff.toFixed(16) }}</td>
                                                            </tr>
                                                        </tbody>
                                                    </table>                                
                                                </v-flex>
                                            </v-layout>
                                            <v-layout v-else>
                                                <v-card-text class="mb-5 mt-5 text-xs-center">
                                                    {{ $t('formType') }}
                                                </v-card-text>                                                
                                            </v-layout>
                                        </v-container>
                                    </template>
                                </v-tabs-content>
                                <v-tabs-content key="tab-02" id="tab-02">
                                    <template>
                                        <v-container grid-list-md>
                                            <v-layout row wrap v-if="canSimulate">
                                                <v-flex md12>
                                                    <v-card-text class="text-xs-center">
                                                        <p>{{ $t('simulate90Days') }}</p>
                                                        <div class="mt-1">
                                                            <v-btn v-on:click="calculateDays" primary dark>{{ $t('calc') }}</v-btn>
                                                        </div>
                                                    </v-card-text>
                                                    <table class="table">
                                                        <thead>
                                                            <tr>
                                                                <th class="text-xs-left">#</th>
                                                                <th class="text-xs-left">{{ $t('day') }}</th>
                                                                <th class="text-xs-left">{{ $t('deposit') }}</th>
                                                                <th class="text-xs-left">{{ $t('value') }}</th>
                                                                <th class="text-xs-left">{{ $t('valueTotal') }}</th>
                                                                <th class="text-xs-left">{{ $t('gain') }}</th>
                                                                <th class="text-xs-left">{{ $t('effective') }}</th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>
                                                            <tr v-for="(data, chave) in simulationDays">
                                                                <td>{{ chave+1 }}</td>
                                                                <td>{{ data.day }}</td>
                                                                <td>
                                                                    <v-text-field
                                                                        v-on:blur="calculateDays"
                                                                        v-model.lazy="data.deposit"
                                                                        type="text"
                                                                    ></v-text-field>
                                                                </td>
                                                                <td>{{ data.value.toFixed(16) }}</td>
                                                                <td>{{ data.valueTotal.toFixed(16) }}</td>
                                                                <td>{{ data.gain.toFixed(16) }}</td>
                                                                <td>{{ data.effective.toFixed(16) }}</td>
                                                            </tr>
                                                        </tbody>
                                                    </table>
                                                </v-flex>
                                            </v-layout>
                                            <v-layout v-else>
                                                <v-card-text class="mb-5 mt-5 text-xs-center">
                                                    {{ $t('formType') }}
                                                </v-card-text>                                                
                                            </v-layout>
                                        </v-container>
                                    </template>
                                </v-tabs-content>
                                <v-tabs-content key="tab-04" id="tab-04">
                                    <template>
                                        <v-container grid-list-md>
                                            <v-layout row wrap>
                                                <v-flex md8 offset-md2 xs12>
                                                    <v-expansion-panel>
                                                        <v-expansion-panel-content v-for="(item,i) in faq" :key="i">
                                                            <div xs12 slot="header">{{ $t(item.title) }}</div>
                                                            <v-card>
                                                                <v-card-text class="grey lighten-3">{{ $t(item.text) }}</v-card-text>
                                                            </v-card>
                                                        </v-expansion-panel-content>
                                                    </v-expansion-panel>
                                                </v-flex>
                                            </v-layout>
                                        </v-container>
                                    </template>
                                </v-tabs-content>
                            </v-tabs-items>
                        </v-tabs>
                        <v-layout row wrap>
                            <v-flex md12 xs12 class="grey lighten-3 text-xs-center">
                                <p class="mt-5 mb-5">{{ $t('codeInGit') }} <a target="_blank" href="https://github.com/Rigolon/daysCalculator">GitHub</a></p>
                            </v-flex>
                        </v-layout>
                    </div>
                </template>
            </main>
        </v-app>
    </div>

    <script src="https://unpkg.com/vue/dist/vue.min.js"></script>
    <script src="https://unpkg.com/vue-i18n/dist/vue-i18n.js"></script>
    <script src="https://unpkg.com/vuetify/dist/vuetify.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/vue-resource/1.3.4/vue-resource.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/limonte-sweetalert2/6.6.10/sweetalert2.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.4/lodash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bignumber.js/4.0.4/bignumber.min.js"></script>
    <script src="/assets/js/v-money.js"></script>
    <script src="/assets/js/translator.js"></script>
    <script src="/assets/js/timemints.js"></script>
    <script src="/assets/js/daysCalculator.js"></script>

    <script>
        var msgAlert       = "Your address is not found in transactions.";
        var msgAlert2      = "The minimum contribution amount is 1 ETH.";
        var msgSuccess     = "Message sent successfully";
        var msgSuccessText = "Your message has been sent successfully. If you have left your contact, we will return with our position.";
        var Oops           = "Oops...";
        var msgErrorText   = "Sorry, we were unable to send your message.";
    </script>
    
</body>
</html>